### ISSUE TITLE
usb timeouts on OS X 10.11.6

### ISSUE THREAD

**Issue by mikest** [python-ivi/python-usbtmc#27]
hello,

i'm getting the following traceback from python when trying to send data to a Rigol mso1104z:

```
>>> import usbtmc
>>> usbtmc.list_devices()
[<DEVICE ID 1ab1:04ce on Bus 020 Address 013>]
>>> ins = usbtmc.Instrument(0x1ab1, 0x04ce)
>>> print(ins.ask("*IDN?"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "usbtmc/usbtmc.py", line 608, in ask
    return self.read(num, encoding)
  File "usbtmc/usbtmc.py", line 591, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "usbtmc/usbtmc.py", line 514, in read_raw
    self.bulk_out_ep.write(req)
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 387, in write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 948, in write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 824, in bulk_write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 920, in __write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno 60] Operation timed out
```

happy to collect more data if it will help.

**Comment by mikest** [comment]
tried Cedric's timeout pull request and got a different error:

```
>>> import usbtmc
>>> usbtmc.Instrument(0x1ab1, 0x04ce)
<usbtmc.usbtmc.Instrument object at 0x101f86f90>
>>> ins = usbtmc.Instrument(0x1ab1, 0x04ce)
>>> print(ins.ask("*IDN?"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "usbtmc/usbtmc.py", line 608, in ask
    return self.read(num, encoding)
  File "usbtmc/usbtmc.py", line 591, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "usbtmc/usbtmc.py", line 516, in read_raw
    resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3, timeout = int(self.timeout*1000))
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 402, in read
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 988, in read
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 833, in bulk_read
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 936, in __read
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno 60] Operation timed out
```

**Comment by mikest** [comment]
tried running code against a DP832 programable power supply. got same timeout issue. seems like maybe there is some OS X funny business going on?

**Comment by alexforencich** [comment]
OS X funny business would not surprise me at all.  Have you tried with any other computers for comparison?

**Comment by alexforencich** [comment]
Oh, can you try that with Cedric's timeout code and an explicit line termination like this?

   print(ins.ask("*IDN?\n"))

or

    print(ins.ask("*IDN?\r\n"))

It's possible that the instrument firmware is expecting a new line char.  Some instruments are programmed properly and are fine with no extra chars, some need a little help.

**Comment by mikest** [comment]
same timeout
```>>> print(ins.ask("*IDN?\r\n"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.macosx-10.11-x86_64/egg/usbtmc/usbtmc.py", line 607, in ask
  File "build/bdist.macosx-10.11-x86_64/egg/usbtmc/usbtmc.py", line 587, in write
  File "build/bdist.macosx-10.11-x86_64/egg/usbtmc/usbtmc.py", line 483, in write_raw
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 387, in write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/core.py", line 948, in write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 824, in bulk_write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 920, in __write
  File "build/bdist.macosx-10.11-x86_64/egg/usb/backend/libusb1.py", line 595, in _check
usb.core.USBError: [Errno 60] Operation timed out
>>>```

got the same error :/

**Comment by luqasz** [comment]
Same error here. Tried both `IDN` commands and I have this exception:
```python
/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usbtmc/usbtmc.pyc in ask(self, message, num, encoding)
    628                 self.lock()
    629             self.write(message, encoding)
--> 630             return self.read(num, encoding)
    631         finally:
    632             if self.advantest_quirk and not was_locked:

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usbtmc/usbtmc.pyc in read(self, num, encoding)
    611     def read(self, num=-1, encoding='utf-8'):
    612         "Read string from instrument"
--> 613         return self.read_raw(num).decode(encoding).rstrip('\r\n')
    614
    615     def ask(self, message, num=-1, encoding='utf-8'):

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usbtmc/usbtmc.pyc in read_raw(self, num)
    530                     self.bulk_out_ep.write(req, timeout=int(self.timeout*1000))
    531
--> 532                 resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3, timeout=int(self.timeout*1000))
    533
    534                 if sys.version_info >= (3, 2):

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usb/core.pyc in read(self, size_or_buffer, timeout)
    400         For details, see the Device.read() method.
    401         """
--> 402         return self.device.read(self, size_or_buffer, timeout)
    403
    404     def clear_halt(self):

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usb/core.pyc in read(self, endpoint, size_or_buffer, timeout)
    986                 intf.bInterfaceNumber,
    987                 buff,
--> 988                 self.__get_timeout(timeout))
    989
    990         if isinstance(size_or_buffer, array.array):

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usb/backend/libusb1.pyc in bulk_read(self, dev_handle, ep, intf, buff, timeout)
    831                            intf,
    832                            buff,
--> 833                            timeout)
    834
    835     @methodtrace(_logger)

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usb/backend/libusb1.pyc in __read(self, fn, dev_handle, ep, intf, buff, timeout)
    934         # do not assume LIBUSB_ERROR_TIMEOUT means no I/O.
    935         if not (transferred.value and retval == LIBUSB_ERROR_TIMEOUT):
--> 936             _check(retval)
    937         return transferred.value
    938

/Users/lkostka/.virtualenvs/tmc/lib/python2.7/site-packages/usb/backend/libusb1.pyc in _check(ret)
    593             raise NotImplementedError(_strerror(ret))
    594         else:
--> 595             raise USBError(_strerror(ret), ret, _libusb_errno[ret])
    596
    597     return ret

USBError: [Errno 60] Operation timed out
```

**Comment by nickovs** [comment]
I'm having the same problem. I have no problem finding my Rigol DS1054z scope on the USB but all commands time out when reading the response. pyUSB 1.0.0, python-usbtmc 0.8 on macOS 10.12.5.

**Comment by alexforencich** [comment]
Rigol firmware does not implement usbtmc correctly. I am seriously considering removing all of the Rigol quirks from the code (they apply primarily to the 1052E, but not the 1000Z, which both share the same VID and PID so it is infeasible to determine which set of quirks to apply) and then just adding a disclaimer that Rigol devices may not work correctly. The Linux kernel driver has the same problem.

**Comment by luqasz** [comment]
> Rigol firmware does not implement usbtmc correctly. I am seriously considering removing all of the Rigol quirks from the code (they apply primarily to the 1052E, but not the 1000Z, which both share the same VID and PID so it is infeasible to determine which set of quirks to apply) and then just adding a disclaimer that Rigol devices may not work correctly. The Linux kernel driver has the same problem.

Maybe leave code with quirks but let users use that one when they need. Default code will be without quirks and for those pesky rigol write a warning and how to use a wrapper class of some kind. Maybe that helps.

**Comment by jbrumf** [comment]
Just a suggestion: How about removing the Rigol quirks from usbtmc.py, but provide a subclass rigol.py that overrides the read_raw method with the quirks. That way, it cleans up usbtmc.py, and only DS1052E users use the subclass.

**Comment by alexforencich** [comment]
Not a bad idea, you would just need a subclass for basically every rigol instrument line as each one seems to implement USBTMC in their own special way.

**Comment by lcvisser** [comment]
For whoever comes here in the future: I had the same issue with a Thorlabs device, but both on Mac OS and Linux (Debian). Thorlabs tech support mailed me a modified version of the usbtmc module that resolved the issue for me. Here's the diff:

```
% diff -w usbtmc.py ThorInstrument.py
487a488,490
>         if self.device.idVendor == 0x1313:
>             self.device.ctrl_transfer(bmRequestType=0xA1, bRequest=USB488_REN_CONTROL, wValue=0x0001, wIndex=0x0000, data_or_wLength=1)
> 
489a493
>         time.sleep(0.1)
491c495
< 
---
>         time.sleep(0.1)
497a502,506
>         if self.device.idVendor == 0x1313:			
>             self.device.ctrl_transfer(bmRequestType=0xA1, bRequest=USB488_GOTO_LOCAL, wValue=0x0000, wIndex=0x0000, data_or_wLength=1)
>             self.device.ctrl_transfer(bmRequestType=0xA1, bRequest=USB488_REN_CONTROL, wValue=0x0000, wIndex=0x0000, data_or_wLength=1)
>             time.sleep(0.1)
```
