### ISSUE TITLE
usb.core.USBError: [Errno None] Configuration not set

### ISSUE THREAD

**Issue by gnbl** [python-ivi/python-usbtmc#28]
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
libusb 1.2.6.0 installed for device with Zadig
pyusb and python-usbtmc first installed with pip

Trying the following

```
    import usbtmc
    import time, sys
    instr =  usbtmc.Instrument(0x1ab1, 0x04ce)
    print(instr.ask("*IDN?"))
    time.sleep(0.2)
    print( "Trigger status:", instr.ask(":TRIGger:STAtus?") )
    time.sleep(0.5)
    print( "Setting single trigger mode.", instr.ask(":SINGle") )
    time.sleep(0.5)
    print( "Trigger status:", instr.ask(":TRIGger:STAtus?") )
    sys.exit()
```

Results in 

```
    print(instr.ask("*IDN?"))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 575, in ask
    self.write(message, encoding)
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 555, in write
    self.write_raw(str(message).encode(encoding))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 464, in write_raw
    self.open()
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 281, in open
    self.old_cfg = self.device.get_active_configuration()
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 875, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 242, in get_active_configuration
    raise USBError('Configuration not set')
usb.core.USBError: [Errno None] Configuration not set
```

Same with python_usbtmc-0.7-py3.5.egg from https://pypi.python.org/pypi/python-usbtmc installed with `easy_install python_usbtmc-0.7-py3.5.egg`

 ```
   print(instr.ask("*IDN?"))
  File "C:\Program Files\Python35\lib\site-packages\python_usbtmc-0.7-py3.5.egg\usbtmc\usbtmc.py", line 575, in ask
  File "C:\Program Files\Python35\lib\site-packages\python_usbtmc-0.7-py3.5.egg\usbtmc\usbtmc.py", line 555, in write
  File "C:\Program Files\Python35\lib\site-packages\python_usbtmc-0.7-py3.5.egg\usbtmc\usbtmc.py", line 464, in write_raw
  File "C:\Program Files\Python35\lib\site-packages\python_usbtmc-0.7-py3.5.egg\usbtmc\usbtmc.py", line 281, in open
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 875, in get_active_configuration
    return self._ctx.get_active_configuration(self)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 102, in wrapper
    return f(self, *args, **kwargs)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 242, in get_active_configuration
    raise USBError('Configuration not set')
usb.core.USBError: [Errno None] Configuration not set
```

Let me know how to provide further debug info.

**Comment by alexforencich** [comment]
Try it again with the latest code from git and let me know if you're still seeing an issue.

**Comment by gnbl** [comment]
Thanks.

```
C:\>pip3 install -U https://github.com/python-ivi/python-usbtmc/archive/master.z
ip
Collecting https://github.com/python-ivi/python-usbtmc/archive/master.zip
  Downloading https://github.com/python-ivi/python-usbtmc/archive/master.zip
     | 30kB 229kB/s
Installing collected packages: python-usbtmc
  Found existing installation: python-usbtmc 0.7
    Uninstalling python-usbtmc-0.7:
      Successfully uninstalled python-usbtmc-0.7
  Running setup.py install for python-usbtmc ... done
Successfully installed python-usbtmc-0.7
```
But not quite:
```
    print(instr.ask("*IDN?"))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 614, in ask
    self.write(message, encoding)
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 594, in write
    self.write_raw(str(message).encode(encoding))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 474, in write_raw
    self.open()
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 305, in open
    for iface in self.old_cfg:
TypeError: 'NoneType' object is not iterable
```
Fix:
```
            # wrong configuration
            # release all kernel drivers
            if self.old_cfg is not None:
                for iface in self.old_cfg:
                    self._release_kernel_driver(iface.bInterfaceNumber)
```
But that gives another error:
```
    print(instr.ask("*IDN?"))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 616, in ask
    return self.read(num, encoding)
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 599, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 522, in read_raw
    self.bulk_out_ep.write(req)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 948, in write
    self.__get_timeout(timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 533, in bulk_write
    data, timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 616, in __write
    timeout
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'
```

**Comment by gnbl** [comment]
Related to https://github.com/python-ivi/python-usbtmc/issues/23 ?
Rigol DS100Z with firmware 00.04.03.SP1

**Comment by alexforencich** [comment]
No, I just didn't fix it completely.  I'm not sitting in front of any USBTMC equipment at the moment, so you'll have to test this for me:

replace usbtmc.py line 304-306:

                # release all kernel drivers
                for iface in self.old_cfg:
                    self._release_kernel_driver(iface.bInterfaceNumber)

with

                # release all kernel drivers
                if self.old_cfg is not None:
                    for iface in self.old_cfg:
                        self._release_kernel_driver(iface.bInterfaceNumber)

and see if that fixes it.

**Comment by gnbl** [comment]
But I already did :-) 
Which then gives the timeout error.

**Comment by alexforencich** [comment]
Oops, sigh.  Didn't read the whole email on my phone.  Looks like something else is going on, then.  Did you try sending the IDN command with a newline after it?

**Comment by alexforencich** [comment]
Actually, this seems to be some other issue as this is a timeout while writing, not while reading.  Have you tried rebooting the scope?

**Comment by gnbl** [comment]
The error is raised for both, write and read, alternatingly, probably because of rigol_quirk.

I have added some output to read_raw:

```
    def read_raw(self, num=-1):
        "Read binary data from instrument"

        if not self.connected:
            self.open()

        read_len = self.max_transfer_size
        if 0 < num < read_len:
            read_len = num

        eom = False

        term_char = None

        if self.term_char is not None:
            term_char = self.term_char

        read_data = b''

        while not eom:
            if not self.rigol_quirk or read_data == b'':

                # if the rigol sees this again, it will restart the transfer
                # so only send it the first time
                print("writing request")
                req = self.pack_dev_dep_msg_in_header(read_len, term_char)
                self.bulk_out_ep.write(req)
            
            print("reading")
            resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3, timeout = int(self.timeout*1000))
```

resulting in 

```
>ds1000z.py
writing request
Traceback (most recent call last):
  File "G:\projects\current\RIGOL_DS1000Z\DS1000Z\ds1000z.py", line 94, in <module>
    print(instr.ask("*IDN?\n"))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 617, in ask
    return self.read(num, encoding)
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 600, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 522, in read_raw
    self.bulk_out_ep.write(req)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 387, in write
    return self.device.write(self, data, timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 948, in write
    self.__get_timeout(timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 533, in bulk_write
    data, timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 616, in __write
    timeout
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

>ds1000z.py
writing request
reading
Traceback (most recent call last):
  File "G:\projects\current\RIGOL_DS1000Z\DS1000Z\ds1000z.py", line 94, in <module>
    print(instr.ask("*IDN?\n"))
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 617, in ask
    return self.read(num, encoding)
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 600, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
  File "C:\Program Files\Python35\lib\site-packages\usbtmc\usbtmc.py", line 525, in read_raw
    resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3, timeout = int(self.timeout*1000))
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 402, in read
    return self.device.read(self, size_or_buffer, timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\core.py", line 988, in read
    self.__get_timeout(timeout))
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 542, in bulk_read
    timeout)
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 627, in __read
    timeout
  File "C:\Program Files\Python35\lib\site-packages\usb\backend\libusb0.py", line 431, in _check
    raise USBError(errmsg, ret)
usb.core.USBError: [Errno None] b'libusb0-dll:err [_usb_reap_async] timeout error\n'

```

Rebooting, re-plugging USB,  and disconnecting the inactive Ethernet connection have had no effect just now.

Replacing the driver installed with zadig  (shows up as Atmel USB Device) with the libusb filter driver did not change anything either. Maybe I have messed up the driver situation.

Playtime is over for me now, I might check back in about 12 hrs. Thanks for your help!

**Comment by gnbl** [comment]
After installing Rigol Ultrasigma including IVI Driver and NI VISA / ICP and then reinstalling the libusb-win32 filter driver things start working again. All these large installs are what I was hoping to avoid. 
Does the IVI driver (IVI Foundation, Inc; 14.08.2013; 16.3.17614.0; ausbtmc.sys) maybe configure the device somehow?
Ethernet with [vxi11](https://github.com/python-ivi/python-vxi11) works without drivers but is noticably slower than USB.

~~I still get a timeout on ```instr.ask(":TRIGger:SWEep SINGle")``` but that must be a firmware issue since other commands are working now.~~
Instrument was lost, says SuperSigma. And the command apparently does not have a response, so write only: ```instr.write(":TRIGger:SWEep SINGle")```.

Thanks again for your help.

**Comment by alexforencich** [comment]
Hmm, that's interesting.  I suppose those drivers could possibly be doing some setup on plug-in that python-usbtmc doesn't do.  It would be interesting to get to the bottom of that.  

It's also interesting that vxi11 is noticably slower.  It should at least be on par, if not faster (presuming gigabit ethernet is supported).  I wonder where the bottleneck is there - is the built-in Ethernet PHY running at 10M or something?  Or is it just a very laggy implementation of vxi11 on the device?  Or is your network adding a lot of latency?

**Comment by gnbl** [comment]
I could try to deinstall the IVI driver and do some logging for you, if you can point me to free software for that purpose.
The Ethernet on the Rigol only has 100 Mbit and apparently a slow implementation, also mentioned elsewhere on the net (eevblog forum I believe). So no worries.

**Comment by alexforencich** [comment]
I think wireshark + usbpcap is probably the best way to do that: http://desowin.org/usbpcap/

**Comment by gnbl** [comment]
I have installed these, and it's still on my list, but don't wait for it..
