### ISSUE TITLE
USBTMC Does not work with USB Hubs on Mac

### ISSUE THREAD

**Issue by jeffsecor** [python-ivi/python-usbtmc#66]
USBTMC Does not work with USB Hubs on Mac

Using thorlabs power meter TPM100D

Works fine with direct connection to computer

Gives Overflow (error 84) or timeout (error 60) when using usb hub.  

Tried different hubs.  Tried different cables.

**Comment by colbyboles** [comment]
I'm here to report the same issue in 2025. I need to get a USB-C to USB-B cable to test what @jeffsecor is saying, that it does work with a direct connection.

My device is a Sigilent SPD1305X power supply. Test code is as follows:

```
import usbtmc

if __name__ == "__main__":
    print(usbtmc.list_devices())
    instr =  usbtmc.Instrument(0xf4ec, 0x1410)
    print(instr)
    print(instr.ask("*IDN?"))
```

Output looks like this:

```
<DEVICE ID f4ec:1410 on Bus 000 Address 005>]
<usbtmc.usbtmc.Instrument object at 0x104ede660>
Traceback (most recent call last):
  File "siglent_psu.py", line 7, in <module>
    print(instr.ask("*IDN?"))
          ~~~~~~~~~^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/usbtmc/usbtmc.py", line 630, in ask
    return self.read(num, encoding)
           ~~~~~~~~~^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/usbtmc/usbtmc.py", line 613, in read
    return self.read_raw(num).decode(encoding).rstrip('\r\n')
           ~~~~~~~~~~~~~^^^^^
  File ".venv/lib/python3.13/site-packages/usbtmc/usbtmc.py", line 532, in read_raw
    resp = self.bulk_in_ep.read(read_len+USBTMC_HEADER_SIZE+3, timeout=int(self.timeout*1000))
  File ".venv/lib/python3.13/site-packages/usb/core.py", line 431, in read
    return self.device.read(self, size_or_buffer, timeout)
           ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.13/site-packages/usb/core.py", line 1043, in read
    ret = fn(
            self._ctx.handle,
    ...<2 lines>...
            buff,
            self.__get_timeout(timeout))
  File ".venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 850, in bulk_read
    return self.__read(self.lib.libusb_bulk_transfer,
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                       dev_handle,
                       ^^^^^^^^^^^
    ...<2 lines>...
                       buff,
                       ^^^^^
                       timeout)
                       ^^^^^^^^
  File ".venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 958, in __read
    _check(retval)
    ~~~~~~^^^^^^^^
  File ".venv/lib/python3.13/site-packages/usb/backend/libusb1.py", line 604, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 84] Overflow
```

**Comment by colbyboles** [comment]
I got a USB-C to USB-B cable to make a direct connection to my M1 MacBook Pro and can now confirm that I no longer get the [Errno 84] Overflow shown above, so I am confirming what @jeffsecor is seeing in terms of this not working with hubs, but working with direct connections to the machine.
